version: '3.0'
services:
  main:
    container_name: main
    build:
      context: .
    ports:
      - "5000:5000"
      - "9229:9229"
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - dmcdb_mariadb
    restart: always

  dmcdb_mariadb:
    image: mariadb:10.10.2
    container_name: dmcdb_mariadb
    command: --default-authentication-plugin=mysql_native_password    
    env_file:
      - .development.mysql.env    
    ports:
      - 3310:3306
    volumes:
      - ./init-mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - dmcdb:/var/lib/mysql
    restart: always

volumes:
  dmcdb:


